#include "codegen.hpp"

void codegen::gen()
{
    // Puts at the start, just to test out
    result += "// Generated by Chirpc\n";
    
    this->gen_toplevel();
}

void codegen::set_tree(ast_root* t, std::string f)
{
    this->m_tree = t;
    this->filename = std::move(f);
}

void codegen::set_cache(cache* c)
{
    this->m_cache = c;
}

std::string&& codegen::get_result()
{
    return std::move(result);  
}
