#include "codegen.hpp"

void codegen::gen()
{
    // Puts at the start, just to test out
    result += "// Generated by Chirpc \n";
    
    this->gen_toplevel();
}

void codegen::set_tree(ast t,std::string f)
{
    this->m_tree = t;
    this->filename = f;
}

void codegen::set_tracker(tracker* t)
{
    this->m_tracker = t;
}

std::string codegen::get_result()
{
    return result;  
}