#include "codegen.hpp"

void codegen::gen()
{
    // Puts at the start, just to test out
    result += "// Generated by Chirpc \n";
}

void codegen::set_tree(ast t)
{
    this->m_tree = t;
}

void codegen::set_tracker(tracker* t)
{
    this->m_tracker = t;
}

std::string codegen::get_result()
{
    return result;  
}